config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/show' => "home#show"
  root "cars#index"

  resources :user_cars, only: [:index]
  resources :cars do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  has_many_attached :images
  has_many :comments, dependent: :destroy

  include Visible

  belongs_to :owner, class_name: "User", foreign_key: "owner_id"


  validates :name, presence: true
  validates :price, presence: true,  length: { minimum: 5 }
  validates :description, presence: true,  length: { minimum: 20 }
  validates :color, presence: true


  VALID_COLORS = ['white', 'black', 'blue', 'grey', 'brown', 'red']

  validates :color, inclusion: { in: VALID_COLORS }

end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :car
  belongs_to :author, class_name: "User", foreign_key: "author_id"

end

app/models/concerns/visible.rb
module Visible extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

class_methods do
    def public_count
      where(status: 'public').count
    end
  end
  def archived?
    status == 'archived'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cars, foreign_key: "owner_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit:: Authorization

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  before_action :authenticate_user!, except: [:index,:show]

  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end

   def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.owner = current_user
    if @car.save
      redirect_to @car
    else
      render :new, status: :unprocessable_entity
    end
  end
 def edit
   @car = Car.find(params[:id])
 end

  def update
    @car = Car.find(params[:id])
    authorize @car
    if @car.update(car_params)
      redirect_to @car
    else
      render :edit, status: :unprocessable_entity
    end
  end

   def destroy
    @car = Car.find(params[:id])
    authorize @car
    @car.destroy

    redirect_to root_path, status: :see_other
  end

   private
    def car_params
      params.require(:car).permit(:name, :price, :description, :color, :status, images: [])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  def create
    @car = Car.find(params[:car_id])
    @comment = Comment.new(comment_params)
    @comment.car = @car
    @comment.author = current_user
    authorize @comment
    @comment.save if @car.owner_id != current_user.id
    redirect_to car_path(@car)
  end

   def destroy
    @car = Car.find(params[:car_id])
    @comment = @car.comments.find(params[:id])
    authorize @comment
    @comment.destroy
    redirect_to car_path(@car), status: :see_other
  end

  private
    def comment_params
      params.require(:comment).permit(:body, :status)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/user_cars_controller.rb
class UserCarsController < ApplicationController
  def index
    @user_cars = current_user.cars
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_cars_helper.rb
module UserCarsHelper
end

app/views/cars/_form.html.erb
<%= form_with model: @car do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @car.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.text_field :price %>
     <% @car.errors.full_messages_for(:price).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

   <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
      <% @car.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

   <div>
    <%= form.label :color %><br>
    <%= form.text_field :color %>
      <% @car.errors.full_messages_for(:color).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>

  <div>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Edit Car</h1>

<%= render "form", car: @car %>

app/views/cars/index.html.erb
<h1>CARS</h1>
<%= link_to "New Car", new_car_path, class: "btn btn-success" %>
<br/>
<p class="fw-light">Found <%= Car.public_count %> cars.</p>


<ul>
  <% @cars.each do |car| %>
    <% unless car.archived? %>
    <li>
      <%= link_to car.name, car %>
    </li>
    <% end %>
  <% end %>
</ul>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render "form", car: @car %>

app/views/cars/show.html.erb
<h1><%= @car.name %></h1>

<% if @car.images.attached? %>
  <% @car.images.each do |image| %>
    <%= image_tag image, {height: "80px", class: "nav-link", style: "border-radius: 5px;"} %>
  <% end %>
<% end %>


<p><b>Price:</b><%= @car.price %></p>

<p>  <b>Color:</b> <%= @car.color %> </p>
<div style="background: <%= @car.color %>; border: 1px solid; width: 10px; height: 10px;"></div>

<p><%= @car.description %></p>

<ul>
  <% if policy(@car).edit? %>
    <li><%= link_to "Edit", edit_car_path(@car) %></li>
  <% end %>
  <% if policy(@car).destroy? %>
    <li><%= link_to "Destroy", car_path(@car), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
  <% end %>
</ul>

<h2>Comments</h2>
<%= render @car.comments %>
<% if policy(@car).comment_create? %>
  <h2>Add a comment:</h2>
  <%=  render 'comments/form'  %>
<%  end %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Author:</strong>
    <%= comment.author.email %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  <p>
  <% if policy(comment).destroy? %>
    <%= link_to "Destroy Comment", [comment.car, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?" } %>
      </p>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @car, @car.comments.build ] do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <div>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</div>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kolesa</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Kolesa</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "CARS", cars_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Language
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Kazakh</a></li>
                <li><a class="dropdown-item" href="#">English</a></li>
                <li><a class="dropdown-item" href="#">Turkish</a></li>
                <li><hr class="dropdown-divider"></li>

                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Another language

                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Russian</a></li>
                  <li><a class="dropdown-item" href="#">Chines</a></li>
                  <li><a class="dropdown-item" href="#">French</a></li>
                </ul>
                  </a>
                 </li>

              </ul>
            </li>

          </ul>
          <form class="d-flex  me-auto mb-2 mb-lg-0" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
          <ul class="navbar-nav">
              <% if current_user %>
                <% if current_user.avatar.attached? %>
                  <li class="nav-item">
                    <%= image_tag current_user.avatar, class: "nav-link avatar-mini-circle" %>
                  </li>
                <% end %>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <%= current_user.email %>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Edit", edit_user_registration_path, class: "dropdown-item" %></li>
                    <li><%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: { turbo_method: :delete } %></li>
                     <li><%= link_to "My cars", user_cars_path, class: "dropdown-item" %></li>
                  </ul>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Login", new_user_session_path, class: "nav-link" %>
                </li>
              <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>

    <div class="container-sm">
      <%= yield %>
    </div>
  </body>
</html>

app/views/user_cars/index.html.erb
<h1>My CARS</h1>
<%= link_to "New Car", new_car_path, class: "btn btn-success" %>
<br/>
<p class="fw-light">Found <%= @user_cars.size %> cars.</p>

<ul>
  <% @user_cars.each do |car| %>
      <li>
        <%= link_to car.name, car %> <%= "archived" if car.archived? %>
      </li>
  <% end %>
</ul>